### ISSUE TITLE
Why use a green ball as maker? How can I use AR code for calibration?

### ISSUE THREAD

**Issue by ubun23** [ravijo/multiple_kinect_baxter_calibration#1]
Thanks for your wonderful work! But I have a question for this calibration code : Why do you use a green ball as maker which I can not obtain. Can you tell me how I can use  AR code for calibration which I can easily obtaion? I am newer for robotic field. Thanks for your kindly reply!

**Comment by ravijo** [comment]
@TZW-056 
Thanks a lot for your words. 

Any marker is fine, as long as you can track it in 3D space. Green ball is easiest to track, so I used it. See the below code snippet:

https://github.com/ravijo/multiple_kinect_baxter_calibration/blob/5b883da744799abbf78f400f40e142d8450a7c9d/src/data_collector_pc.cpp#L288

Here, you can use other markers and record that marker position with respect to camera. Hope it helps!

**Comment by ubun23** [comment]
I am so excited for your quick and kind reply and  I successfully run this repo in my workspace with a green 
balloon. But the result is not so satisfying.  The calibration error is 9.57 cm and  I do not know that exactly mean. 
![Screenshot from 2024-04-18 17-42-14](https://github.com/ravijo/multiple_kinect_baxter_calibration/assets/61307054/5eaeff6e-97dd-4147-930d-b31ceaeeea31)
![Screenshot from 2024-04-18 17-43-39](https://github.com/ravijo/multiple_kinect_baxter_calibration/assets/61307054/0280007e-e54b-4926-9572-fea72d0bffd7)


And I have some questions for this repo. Hope you can kindly explain for me!
1. when I run the `calibration_data_collector.launch` , an error occured : ` Couldn't record any data. Run the program again.` Just like below. And `[Kinect2Bridge::main] waiting for clients to connect` in the `kinect2_bridge.launch`.  I guess if the kinect v2 do not successful used. But there are `Successfully detected sphere 0 times out of 5` in the `calibration_data_collector.launch`.
2. After successfully calibrate baxter and kinect, what should I do to conver the grasp pose in kinect 
coordinate system to baxter coordinate system.
![Screenshot from 2024-04-18 17-44-59](https://github.com/ravijo/multiple_kinect_baxter_calibration/assets/61307054/9fb6b4e7-82ef-4419-8ddd-5979e896ccb3)


Thanks for your kindly reply though I am newcomer to  robotic. :smile: :+1:
